apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: jerome/configserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8071